baseURL = "https://pankona.github.io"
title = "make clean; make"
hasCJKLanguage = true
author = "pankona"
pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsStyle = "monokai"
theme = "purehugo"

[pagination]
pagerSize = 20

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "atom"

[mediaTypes]
[mediaTypes."image/x-icon"]
suffixes = ["ico"]

[params]
description = "Good poem"
twitterName = "pankona"
twitter = ""
githubName = "pankona"
image = "https://avatars1.githubusercontent.com/u/6533008?s=460&v=4"
paginate = 20

[permalinks]
posts = "/blog/:year/:month/:day/:contentbasename/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
hardWraps = true
