name: CI - Nix
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nix.yml'
      - '*.nix'
      - 'flake.*'
      - '.envrc'
      - 'Makefile'
      - 'print_dependencies.bash'
  pull_request:
    paths:
      - '.github/workflows/ci-nix.yml'
      - '*.nix'
      - 'flake.*'
      - '.envrc'
      - 'Makefile'
      - 'print_dependencies.bash'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: nix flake check
      - name: Install direnv
        run: |
          url="$(nix eval --raw --impure --expr '(builtins.fromJSON (builtins.readFile ./flake.lock)).nodes.nixpkgs.locked.url')"
          nix profile add "${url}#direnv"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - run: make deps
      - run: make all
