name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  typo:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@v1.44.0
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635761199
          files: |
            .
            .github
            .vscode
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dprint/check@v2.3
      - name: Debug print for deprint target paths
        run: dprint output-file-paths

  markdownlint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: rvben/rumdl@7dda9cdd0817f87be77adb1e93edaf7e418b001e # v0
        with:
          version: '0.0.194'
