name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  typo:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@v1.47.1
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635761199
          files: |
            .
            .github
            .vscode
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dprint/check@v2.3
      - name: Debug print for deprint target paths
        run: dprint output-file-paths

  markdownlint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: rvben/rumdl@546bd21b33a0401441a60d8f0c15431458ea6ab9 # v0
        with:
          version: '0.2.5'
